"""Date with time (isoformat)"""
scalar DateTime
scalar Snowflake

type DeleteResult {
  code: Int!
  successMsg: String
  errors: [String!]!
}

type Guild implements Server {
  guildId: Snowflake!
  name: String!
  status: String
  settings: JSON!
  dateAdded: DateTime
  lastAct: LastAct!
  idleStats: IdleStats!
  members: [Member!]!
}

input GuildCreate {
  guildId: Snowflake!
  name: String!
}

type GuildMutations {
  createGuild(input: GuildCreate!): GuildResult!
  createGuilds(bulkData: GuildsCreate!): GuildsResult!
  updateGuild(guildId: Snowflake!, input: GuildUpdate!): GuildResult!
  resetGuild(guildId: Snowflake!): GuildResult!
  deleteGuild(guildId: Snowflake!): DeleteResult!
}

type GuildQueries {
  guild(snowflake: Snowflake!): GuildResult!
  guilds: GuildsResult!
}

type GuildResult {
  code: Int!
  success: Boolean!
  created: Boolean
  errors: [String!]!
  guild: Guild
}

input GuildUpdate {
  lastAct: UpdateLastAct
  idleStats: UpdateIdleStats
  status: String
  settings: JSON
}

input GuildsCreate {
  guilds: [GuildCreate!]!
}

input GuildCreate {
  guilds: GuildCreate!
}

type GuildsResult {
  code: Int!
  success: Boolean!
  errors: [String!]!
  guilds: [Guild!]!
}

type IdleStats {
  timesIdle: [Int!]!
  prevAvgs: [Int!]!
}

scalar JSON

type LastAct {
  ch: Snowflake
  type: String
  ts: DateTime
}

type Member implements User {
  memberId: Snowflake!
  username: String!
  guildId: Snowflake!
  adminAccess: Boolean
  dateAdded: DateTime
  flags: [String!]
  lastAct: LastAct!
  idleStats: IdleStats!
  status: String
}

input MemberCreate {
  memberId: Snowflake!
  username: String!
  flags: [String!]
}

type MemberMutations {
  createMember(guildId: Snowflake!, input: MemberCreate!): MemberResult!
  updateMember(memberId: Snowflake!, guildId: Snowflake!, input: MemberUpdate!): MemberResult!
  deleteMember(memberId: Snowflake!, guildId: Snowflake!): DeleteResult!
}

type MemberQueries {
  member(memberId: Snowflake!, guildId: Snowflake!): MemberResult!
  members(guildId: Snowflake!): MembersResult!
}

type MemberResult {
  code: Int!
  success: Boolean!
  created: Boolean
  errors: [String!]!
  member: Member
}

input MemberUpdate {
  username: String
  adminAccess: Boolean
  lastAct: UpdateLastAct
  idleStats: UpdateIdleStats
  flags: [String!]
  status: String
}

type MembersResult {
  code: Int!
  success: Boolean!
  errors: [String!]!
  members: [Member!]!
}

type Mutation {
  guild: GuildMutations!
  member: MemberMutations!
}

type Query {
  member: MemberQueries!
  guild: GuildQueries!
}

interface Server {
  guildId: Snowflake!
  status: String
  settings: JSON
  dateAdded: DateTime
}

input UpdateIdleStats {
  timesIdle: [Int!]!
  prevAvgs: [Int!]!
}

input UpdateLastAct {
  ch: Snowflake
  type: String!
  ts: DateTime!
}

interface User {
  memberId: Snowflake!
  adminAccess: Boolean
  dateAdded: DateTime
  flags: [String!]
}
