"""Renaming snowflake col back to <model>_id

Revision ID: 0be739ed0c47
Revises: 5c28bd41f895
Create Date: 2025-09-16 10:54:48.122087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0be739ed0c47"
down_revision: Union[str, Sequence[str], None] = "5c28bd41f895"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guilds", sa.Column("guild_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(op.f("guilds_snowflake_key"), "guilds", type_="unique")
    op.create_unique_constraint(None, "guilds", ["guild_id"])
    op.drop_column("guilds", "snowflake")
    op.add_column(
        "member_shards",
        sa.Column("member_id", sa.BigInteger(), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_snowflake_guild"), "member_shards", type_="unique"
    )
    op.create_unique_constraint(
        "uq_member_guild", "member_shards", ["member_id", "guild_id"]
    )
    op.drop_column("member_shards", "snowflake")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_shards",
        sa.Column(
            "snowflake", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("uq_member_guild", "member_shards", type_="unique")
    op.create_unique_constraint(
        op.f("uq_snowflake_guild"),
        "member_shards",
        ["snowflake", "guild_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("member_shards", "member_id")
    op.add_column(
        "guilds",
        sa.Column(
            "snowflake", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "guilds", type_="unique")
    op.create_unique_constraint(
        op.f("guilds_snowflake_key"),
        "guilds",
        ["snowflake"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("guilds", "guild_id")
    # ### end Alembic commands ###
