"""Adding flags column

Revision ID: 17320bc8d3b3
Revises: e2538d242e3b
Create Date: 2025-09-04 14:16:12.672611

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17320bc8d3b3"
down_revision: Union[str, Sequence[str], None] = "e2538d242e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guilds", sa.Column("flags", sa.ARRAY(sa.String()), nullable=False)
    )
    op.alter_column(
        "guilds",
        "prev_avgs",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guilds",
        "prev_avgs",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=True,
    )
    op.drop_column("guilds", "flags")
    # ### end Alembic commands ###
