"""removes discriminator and renames username to name

Revision ID: 248050dc083d
Revises:
Create Date: 2025-09-02 12:50:14.327967

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "248050dc083d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = (
    "rm_discriminator_rename_username",
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_shards", sa.Column("name", sa.String(), nullable=False)
    )
    op.drop_constraint(
        op.f("member_shards_guild_id_fkey"),
        "member_shards",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "member_shards", "guilds", ["guild_id"], ["id"]
    )
    op.drop_column("member_shards", "username")
    op.drop_column("member_shards", "discriminator")
    op.drop_column("member_shards", "nickname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_shards",
        sa.Column(
            "nickname",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "member_shards",
        sa.Column(
            "discriminator", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "member_shards",
        sa.Column(
            "username", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "member_shards", type_="foreignkey")
    op.create_foreign_key(
        op.f("member_shards_guild_id_fkey"),
        "member_shards",
        "guilds",
        ["guild_id"],
        ["snowflake"],
    )
    op.drop_column("member_shards", "name")
    # ### end Alembic commands ###
