"""Moving flags column from Guild to MemberShard

Revision ID: 2da5b28bd7b7
Revises: 17320bc8d3b3
Create Date: 2025-09-04 14:35:01.985069

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2da5b28bd7b7"
down_revision: Union[str, Sequence[str], None] = "17320bc8d3b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guilds", "flags")
    op.add_column(
        "member_shards",
        sa.Column("flags", sa.ARRAY(sa.String()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member_shards", "flags")
    op.add_column(
        "guilds",
        sa.Column(
            "flags",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
