"""add username field back

Revision ID: 3aed77b8a7c7
Revises: e82dc212aaaa
Create Date: 2026-07-14 14:46:42.606287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3aed77b8a7c7"
down_revision: Union[str, Sequence[str], None] = "e82dc212aaaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "member_shards",
        sa.Column("username", sa.String(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
