"""Removes name and avg_idle_time columns

Revision ID: 5c28bd41f895
Revises: 2da5b28bd7b7
Create Date: 2025-09-15 20:58:26.268766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c28bd41f895"
down_revision: Union[str, Sequence[str], None] = "2da5b28bd7b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guilds", "name")
    op.drop_column("guilds", "avg_idle_time")
    op.drop_column("member_shards", "avg_idle_time")
    op.drop_column("member_shards", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_shards",
        sa.Column(
            "name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "member_shards",
        sa.Column(
            "avg_idle_time", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "guilds",
        sa.Column(
            "avg_idle_time", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "guilds",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
