"""defaults to Guild.settings

Revision ID: 789890d1b952
Revises: 2da5b28bd7b7
Create Date: 2025-09-05 00:46:11.265114

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "789890d1b952"
down_revision: Union[str, Sequence[str], None] = "2da5b28bd7b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
