"""add name field back to guild

Revision ID: 7cb24a131b1a
Revises: 3aed77b8a7c7
Create Date: 2026-07-14 18:09:02.557528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7cb24a131b1a"
down_revision: Union[str, Sequence[str], None] = "3aed77b8a7c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guilds",
        sa.Column("name", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guilds", "name")
    # ### end Alembic commands ###
