"""Change Guild.members relationship to dynamic for scalability

Revision ID: a53770e620ae
Revises: 789890d1b952
Create Date: 2025-09-05 20:46:04.951036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a53770e620ae"
down_revision: Union[str, Sequence[str], None] = "789890d1b952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
