"""Removes unique constraint from MemberShard and adds a composite instead.

Revision ID: cf590613ebda
Revises: 248050dc083d
Create Date: 2025-09-02 15:24:13.605566

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf590613ebda"
down_revision: Union[str, Sequence[str], None] = "248050dc083d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("member_shards_snowflake_key"), "member_shards", type_="unique"
    )
    op.create_unique_constraint(
        "uq_snowflake_guild", "member_shards", ["snowflake", "guild_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_snowflake_guild", "member_shards", type_="unique")
    op.create_unique_constraint(
        op.f("member_shards_snowflake_key"),
        "member_shards",
        ["snowflake"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
