"""changes

Revision ID: e2538d242e3b
Revises: cf590613ebda
Create Date: 2025-09-03 16:06:32.278597

"""

# Standard modules
from typing import Sequence, Union

# Third party modules
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Internal modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2538d242e3b"
down_revision: Union[str, Sequence[str], None] = "cf590613ebda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guilds",
        "settings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guilds",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    # ### end Alembic commands ###
