"""Removes last_act_server column from MemberShard

Revision ID: e82dc212aaaa
Revises: 0be739ed0c47
Create Date: 2025-09-16 11:41:17.883865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e82dc212aaaa"
down_revision: Union[str, Sequence[str], None] = "0be739ed0c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member_shards", "last_act_server")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_shards",
        sa.Column(
            "last_act_server", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
